"""removed latest message id

Revision ID: cf8eaa1e21f1
Revises: 5c9b8d15d6bf
Create Date: 2023-12-27 15:41:12.949734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8eaa1e21f1'
down_revision: Union[str, None] = '5c9b8d15d6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('latest_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'messages', ['latest_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'latest_message_id')
    # ### end Alembic commands ###
