"""removed received_messages relationship in user and translation tables

Revision ID: b8c0579e739b
Revises: 674326c5f1ea
Create Date: 2023-12-28 17:13:02.702299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c0579e739b'
down_revision: Union[str, None] = '674326c5f1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
