"""remove default value for is_read column of translation table

Revision ID: 16dba94bc2da
Revises: 367a41c75ca2
Create Date: 2023-12-29 19:15:03.841727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16dba94bc2da'
down_revision: Union[str, None] = '367a41c75ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
