"""added convo photo and latest message id

Revision ID: 75410ea24476
Revises: e11af1d07d2c
Create Date: 2023-12-27 12:42:39.394050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75410ea24476"
down_revision: Union[str, None] = "e11af1d07d2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column("conversation_photo", sa.String(length=255), nullable=True),
    )
    op.add_column("conversations", sa.Column("latest_message_id", sa.Integer()))
    op.create_foreign_key(
        None, "conversations", "messages", ["latest_message_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "conversations", type_="foreignkey")
    op.drop_column("conversations", "latest_message_id")
    op.drop_column("conversations", "conversation_photo")
    # ### end Alembic commands ###
