"""removed latest message id

Revision ID: 5c9b8d15d6bf
Revises: 75410ea24476
Create Date: 2023-12-27 15:12:47.962557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9b8d15d6bf'
down_revision: Union[str, None] = '75410ea24476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_latest_message_id_fkey', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'latest_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('latest_message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('conversations_latest_message_id_fkey', 'conversations', 'messages', ['latest_message_id'], ['id'])
    # ### end Alembic commands ###
