"""indexed User.email, Conversation.latest_msg_id; created Composite Index for Translation w/ message_id, target_user_id

Revision ID: 719b0c1ffc60
Revises: 7a4f6e3d031e
Create Date: 2024-03-13 14:30:22.063466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719b0c1ffc60'
down_revision: Union[str, None] = '7a4f6e3d031e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conversations_latest_message_id'), 'conversations', ['latest_message_id'], unique=False)
    op.create_index('idx_message_id_target_user_id', 'translations', ['message_id', 'target_user_id'], unique=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index('idx_message_id_target_user_id', table_name='translations')
    op.drop_index(op.f('ix_conversations_latest_message_id'), table_name='conversations')
    # ### end Alembic commands ###
