"""added pwd_changed column to User table

Revision ID: 2e2526fccf6b
Revises: fca5b6026dd3
Create Date: 2024-02-17 15:26:02.566081

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e2526fccf6b"
down_revision: Union[str, None] = "fca5b6026dd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add the column as nullable initially
    op.add_column("users", sa.Column("pwd_changed", sa.DateTime(), nullable=True))

    # Step 2: Update existing rows with the current UTC timestamp
    op.execute("UPDATE users SET pwd_changed = timezone('UTC', CURRENT_TIMESTAMP)")

    # Step 3: Alter the column to NOT NULL after updating existing rows
    op.alter_column("users", "pwd_changed", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "pwd_changed")
    # ### end Alembic commands ###
