"""added a chat_identifier column to conversations table

Revision ID: bec34a2a8f20
Revises: 8efb481064fb
Create Date: 2024-03-21 20:39:45.037914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bec34a2a8f20"
down_revision: Union[str, None] = "8efb481064fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column("chat_identifier", sa.String(length=64), nullable=True),
    )
    op.execute("UPDATE conversations SET chat_identifier = 'abc'")
    op.alter_column("conversations", "chat_identifier", nullable=False)

    op.create_index(
        op.f("ix_conversations_chat_identifier"),
        "conversations",
        ["chat_identifier"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversations_chat_identifier"), table_name="conversations")
    op.drop_column("conversations", "chat_identifier")
    # ### end Alembic commands ###
