"""added api_key column to user

Revision ID: c01d054d491b
Revises: b6ff2b988e81
Create Date: 2024-03-08 21:24:43.449977

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c01d054d491b"
down_revision: Union[str, None] = "b6ff2b988e81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("api_key", sa.String(length=255), nullable=True))

    op.execute(
        "UPDATE users SET api_key = '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'"
    )

    op.alter_column("users", "api_key", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "api_key")
    # ### end Alembic commands ###
