"""composite index on Message.conversation_id and Message.sent_at.desc()

Revision ID: 8efb481064fb
Revises: 719b0c1ffc60
Create Date: 2024-03-18 12:39:43.131376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efb481064fb'
down_revision: Union[str, None] = '719b0c1ffc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_conversation_id_sent_at', 'messages', ['conversation_id', sa.text('sent_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_conversation_id_sent_at', table_name='messages')
    # ### end Alembic commands ###
