"""no latest_message column and latest_message_id no foreign key to Message

Revision ID: 7a4f6e3d031e
Revises: c01d054d491b
Create Date: 2024-03-09 20:00:47.115697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4f6e3d031e'
down_revision: Union[str, None] = 'c01d054d491b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_latest_message_id_fkey', 'conversations', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('conversations_latest_message_id_fkey', 'conversations', 'messages', ['latest_message_id'], ['id'])
    # ### end Alembic commands ###
