"""changing profile_photo maximum length

Revision ID: fca5b6026dd3
Revises: 5c962462dbe9
Create Date: 2024-02-13 19:48:45.917132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca5b6026dd3'
down_revision: Union[str, None] = '5c962462dbe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_photo',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=4096),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_photo',
               existing_type=sa.String(length=4096),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
